=== Eloy-i/MyInsuApp/docs/xml/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Informe">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Paciente" type="TipoPaciente"/>
                <xs:element name="ResumenInyecciones" type="TipoResumen"/>
                <xs:element name="Zonas" type="TipoZonas"/>
            </xs:sequence>
            <xs:attribute name="fecha" type="xs:date" use="required"/>
            <xs:attribute name="rangoDias" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="TipoPaciente">
        <xs:sequence>
            <xs:element name="Nombre">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="3"/>
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Edad">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="120"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="TipoDiabetes" type="EnumDiabetes"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TipoResumen">
        <xs:sequence>
            <xs:element name="TotalInsulinaUsada" type="DecimalDosPuntos"/>
            <xs:element name="PromedioInsulinaDiaria" type="DecimalDosPuntos"/>
            <xs:element name="DosisMaxima">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0.0"/>
                        <xs:maxInclusive value="30.0"/>
                        <xs:fractionDigits value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="TotalInyecciones" type="xs:integer"/>
            <xs:element name="TotalIncidencias" type="xs:integer"/>
            <xs:element name="MediaInyeccionesDiarias" type="DecimalDosPuntos"/>
            <xs:element name="ZonaMasUsada" type="EnumZonas"/>
            <xs:element name="ZonaMasIncidencias" type="EnumZonas"/>
            <xs:element name="PorcentajeIncidencias">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0.00"/>
                        <xs:maxInclusive value="100.00"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TipoZonas">
        <xs:sequence>
            <xs:element name="Zona" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="EventoInyeccion" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="tipo" type="EnumEventos" use="required"/>
                                <xs:attribute name="cantidad" type="xs:integer" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="nombre" type="EnumZonas" use="required"/>
                    <xs:attribute name="totalInyecciones" type="xs:integer" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="EnumDiabetes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Tipo 1"/>
            <xs:enumeration value="Tipo 2"/>
            <xs:enumeration value="LADA"/>
            <xs:enumeration value="Gestacional"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="EnumZonas">
        <xs:restriction base="xs:string">
            <xs:enumeration value="abdomen izquierdo"/>
            <xs:enumeration value="abdomen derecho"/>
            <xs:enumeration value="muslo izquierdo"/>
            <xs:enumeration value="muslo derecho"/>
            <xs:enumeration value="gluteo izquierdo"/>
            <xs:enumeration value="gluteo derecho"/>
            <xs:enumeration value="triceps izquierdo"/>
            <xs:enumeration value="triceps derecho"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="EnumEventos">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sangrado"/>
            <xs:enumeration value="dolor agudo"/>
            <xs:enumeration value="bola insulina"/>
            <xs:enumeration value="Sin incidencia"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DecimalDosPuntos">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Eloy-i/MyInsuApp/docs/xml/informe_DemoDemirez_2026-05-02_15días.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Informe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" fecha="2026-05-02" rangoDias="15" xsi:noNamespaceSchemaLocation="esquema.xsd">
    <Paciente>
        <Nombre>Demo Demirez</Nombre>
        <Edad>26</Edad>
        <TipoDiabetes>LADA</TipoDiabetes>
    </Paciente>
    <ResumenInyecciones>
        <TotalInsulinaUsada>78.5</TotalInsulinaUsada>
        <PromedioDiario>5.23</PromedioDiario>
        <DosisMaxima>12.5</DosisMaxima>
        <TotalInyecciones>13</TotalInyecciones>
        <TotalIncidencias>6</TotalIncidencias>
        <MediaInyeccionesDiarias>0.87</MediaInyeccionesDiarias>
        <ZonaMasUsada>gluteo derecho</ZonaMasUsada>
        <ZonaMasIncidencias>gluteo derecho</ZonaMasIncidencias>
        <PorcentajeIncidencias>46.15</PorcentajeIncidencias>
    </ResumenInyecciones>
    <Zonas>
        <Zona nombre="abdomen izquierdo" totalInyecciones="4">
            <EventoInyeccion tipo="Sin incidencia" cantidad="2"/>
            <EventoInyeccion tipo="dolor agudo" cantidad="1"/>
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
        <Zona nombre="gluteo izquierdo" totalInyecciones="1">
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
        <Zona nombre="muslo izquierdo" totalInyecciones="1">
            <EventoInyeccion tipo="Sin incidencia" cantidad="1"/>
        </Zona>
        <Zona nombre="triceps derecho" totalInyecciones="3">
            <EventoInyeccion tipo="Sin incidencia" cantidad="3"/>
        </Zona>
        <Zona nombre="gluteo derecho" totalInyecciones="4">
            <EventoInyeccion tipo="bola insulina" cantidad="1"/>
            <EventoInyeccion tipo="Sin incidencia" cantidad="1"/>
            <EventoInyeccion tipo="dolor agudo" cantidad="2"/>
        </Zona>
    </Zonas>
</Informe>

=== Eloy-i/MyInsuApp/docs/xml/informe_DemoDemirez_2026-05-03_1días.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Informe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" fecha="2026-05-03" rangoDias="1" xsi:noNamespaceSchemaLocation="esquema.xsd">
    <Paciente>
        <Nombre>Demo Demirez</Nombre>
        <Edad>26</Edad>
        <TipoDiabetes>LADA</TipoDiabetes>
    </Paciente>
    <ResumenInyecciones>
        <TotalInsulinaUsada>22.5</TotalInsulinaUsada>
        <PromedioDiario>22.5</PromedioDiario>
        <DosisMaxima>8.0</DosisMaxima>
        <TotalInyecciones>5</TotalInyecciones>
        <TotalIncidencias>2</TotalIncidencias>
        <MediaInyeccionesDiarias>5.0</MediaInyeccionesDiarias>
        <ZonaMasUsada>triceps derecho</ZonaMasUsada>
        <ZonaMasIncidencias>muslo izquierdo</ZonaMasIncidencias>
        <PorcentajeIncidencias>40.0</PorcentajeIncidencias>
    </ResumenInyecciones>
    <Zonas>
        <Zona nombre="abdomen izquierdo" totalInyecciones="1">
            <EventoInyeccion tipo="Sin incidencia" cantidad="1"/>
        </Zona>
        <Zona nombre="muslo izquierdo" totalInyecciones="1">
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
        <Zona nombre="triceps derecho" totalInyecciones="2">
            <EventoInyeccion tipo="bola insulina" cantidad="1"/>
            <EventoInyeccion tipo="Sin incidencia" cantidad="1"/>
        </Zona>
        <Zona nombre="triceps izquierdo" totalInyecciones="1">
            <EventoInyeccion tipo="Sin incidencia" cantidad="1"/>
        </Zona>
    </Zonas>
</Informe>

=== Eloy-i/MyInsuApp/docs/xml/informe_2026-04-29_30días(Erroneo).xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Informe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" fecha="202-04-29" rangoDias="30" xsi:noNamespaceSchemaLocation="esquema.xsd">
    <Paciente>
        <Nombre>Felipe Juan Froilán de Todos los Santos de Marichalar y Borbón de la Santísima Trinidad de Grecia y Dinamarca</Nombre>
        <Edad>126</Edad>
        <TipoDiabetes>Ciruelo</TipoDiabetes>
    </Paciente>
    <ResumenInyecciones>
        <TotalInsulinaUsada>238.5</TotalInsulinaUsada>
        <PromedioDiario>7.95</PromedioDiario>
        <DosisMaxima>52.5</DosisMaxima>
        <TotalInyecciones>47</TotalInyecciones>
        <TotalIncidencias>10</TotalIncidencias>
        <MediaInyeccionesDiarias>1.57</MediaInyeccionesDiarias>
        <ZonaMasUsada>abdomen izquierdo</ZonaMasUsada>
        <ZonaMasIncidencias>Vallecas</ZonaMasIncidencias>
        <PorcentajeIncidencias>21.28</PorcentajeIncidencias>
    </ResumenInyecciones>
    <Zonas>
        <Zona nombre="abdomen izquierdo" totalInyecciones="19">
            <EventoInyeccion tipo="Sin incidencia" cantidad="16"/>
            <EventoInyeccion tipo="89" cantidad="dos"/>
            <EventoInyeccion tipo="sangrado" cantidad="2"/>
        </Zona>
        <Zona nombre="gluteo izquierdo" totalInyecciones="1">
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
        <Zona nombre="muslo izquierdo" totalInyecciones="2">
            <EventoInyeccion tipo="Sin incidencia" cantidad="2"/>
        </Zona>
        <Zona nombre="abdomen derecho" totalInyecciones="1">
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
        <Zona nombre="muslo derecho" totalInyecciones="1">
            <EventoInyeccion tipo="Sin incidencia" cantidad="1"/>
        </Zona>
        <Zona nombre="triceps derecho" totalInyecciones="4">
            <EventoInyeccion tipo="Sin incidencia" cantidad="3"/>
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
        <Zona nombre="triceps izquierdo" totalInyecciones="15">
            <EventoInyeccion tipo="bola insulina" cantidad="1"/>
            <EventoInyeccion tipo="Sin incidencia" cantidad="14"/>
        </Zona>
        <Zona nombre="gluteo derecho" totalInyecciones="4">
            <EventoInyeccion tipo="bola insulina" cantidad="1"/>
            <EventoInyeccion tipo="Sin incidencia" cantidad="1"/>
            <EventoInyeccion tipo="dolor agudo" cantidad="1"/>
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
    </Zonas>
</Informe>

=== Eloy-i/MyInsuApp/docs/xml/informe_2026-04-29_30días(Erroneo-orden).xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Informe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" fecha="206-04-29" rangoDias="30" xsi:noNamespaceSchemaLocation="esquema.xsd">
    <ResumenInyecciones>
        <TotalInsulinaUsada>238.5</TotalInsulinaUsada>
        <PromedioDiario>7.95</PromedioDiario>
        <DosisMaxima>12.5</DosisMaxima>
        <TotalInyecciones>47</TotalInyecciones>
        <TotalIncidencias>10</TotalIncidencias>
        <MediaInyeccionesDiarias>1.57</MediaInyeccionesDiarias>
        <ZonaMasUsada>abdomen izquierdo</ZonaMasUsada>
        <ZonaMasIncidencias>abdomen izquierdo</ZonaMasIncidencias>
        <PorcentajeIncidencias>21.28</PorcentajeIncidencias>
    </ResumenInyecciones>

    <Paciente>
        <Nombre>Demo Demirez</Nombre>
        <TipoDiabetes>LADA</TipoDiabetes>
        <Edad>26</Edad>
    </Paciente>

    <Zonas>
        <Zona nombre="abdomen izquierdo" totalInyecciones="19">
            <EventoInyeccion tipo="Sin incidencia" cantidad="16"/>
            <EventoInyeccion tipo="dolor agudo" cantidad="1"/>
            <EventoInyeccion tipo="sangrado" cantidad="2"/>
        </Zona>
        <Zona nombre="gluteo izquierdo" totalInyecciones="1">
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
        <Zona nombre="muslo izquierdo" totalInyecciones="2">
            <EventoInyeccion tipo="Sin incidencia" cantidad="2"/>
        </Zona>
        <Zona nombre="abdomen derecho" totalInyecciones="1">
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
        <Zona nombre="muslo derecho" totalInyecciones="1">
            <EventoInyeccion tipo="Sin incidencia" cantidad="1"/>
        </Zona>
        <Zona nombre="triceps derecho" totalInyecciones="4">
            <EventoInyeccion tipo="Sin incidencia" cantidad="3"/>
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
        <Zona nombre="triceps izquierdo" totalInyecciones="15">
            <EventoInyeccion tipo="bola insulina" cantidad="1"/>
            <EventoInyeccion tipo="Sin incidencia" cantidad="14"/>
        </Zona>
        <Zona nombre="gluteo derecho" totalInyecciones="4">
            <EventoInyeccion tipo="bola insulina" cantidad="1"/>
            <EventoInyeccion tipo="Sin incidencia" cantidad="1"/>
            <EventoInyeccion tipo="dolor agudo" cantidad="1"/>
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
    </Zonas>
</Informe>

=== Eloy-i/MyInsuApp/docs/xml/informe_2026-05-02_1días.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Informe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" fecha="2026-05-02" rangoDias="1" xsi:noNamespaceSchemaLocation="esquema.xsd">
    <Paciente>
        <Nombre>Demo Demirez</Nombre>
        <Edad>26</Edad>
        <TipoDiabetes>LADA</TipoDiabetes>
    </Paciente>
    <ResumenInyecciones>
        <TotalInsulinaUsada>7.0</TotalInsulinaUsada>
        <PromedioDiario>7.0</PromedioDiario>
        <DosisMaxima>6.0</DosisMaxima>
        <TotalInyecciones>2</TotalInyecciones>
        <TotalIncidencias>1</TotalIncidencias>
        <MediaInyeccionesDiarias>2.0</MediaInyeccionesDiarias>
        <ZonaMasUsada>abdomen izquierdo</ZonaMasUsada>
        <ZonaMasIncidencias>gluteo derecho</ZonaMasIncidencias>
        <PorcentajeIncidencias>50.0</PorcentajeIncidencias>
    </ResumenInyecciones>
    <Zonas>
        <Zona nombre="abdomen izquierdo" totalInyecciones="1">
            <EventoInyeccion tipo="Sin incidencia" cantidad="1"/>
        </Zona>
        <Zona nombre="gluteo derecho" totalInyecciones="1">
            <EventoInyeccion tipo="dolor agudo" cantidad="1"/>
        </Zona>
    </Zonas>
</Informe>

=== Eloy-i/MyInsuApp/docs/xml/informe_2026-04-29_30días.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Informe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" fecha="2026-04-29" rangoDias="30" xsi:noNamespaceSchemaLocation="esquema.xsd">
    <Paciente>
        <Nombre>Demo Demirez</Nombre>
        <Edad>26</Edad>
        <TipoDiabetes>LADA</TipoDiabetes>
    </Paciente>
    <ResumenInyecciones>
        <TotalInsulinaUsada>238.5</TotalInsulinaUsada>
        <PromedioInsulinaDiaria>7.95</PromedioInsulinaDiaria>
        <DosisMaxima>12.5</DosisMaxima>
        <TotalInyecciones>47</TotalInyecciones>
        <TotalIncidencias>10</TotalIncidencias>
        <MediaInyeccionesDiarias>1.57</MediaInyeccionesDiarias>
        <ZonaMasUsada>abdomen izquierdo</ZonaMasUsada>
        <ZonaMasIncidencias>abdomen izquierdo</ZonaMasIncidencias>
        <PorcentajeIncidencias>21.28</PorcentajeIncidencias>
    </ResumenInyecciones>
    <Zonas>
        <Zona nombre="abdomen izquierdo" totalInyecciones="19">
            <EventoInyeccion tipo="Sin incidencia" cantidad="16"/>
            <EventoInyeccion tipo="dolor agudo" cantidad="1"/>
            <EventoInyeccion tipo="sangrado" cantidad="2"/>
        </Zona>
        <Zona nombre="gluteo izquierdo" totalInyecciones="1">
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
        <Zona nombre="muslo izquierdo" totalInyecciones="2">
            <EventoInyeccion tipo="Sin incidencia" cantidad="2"/>
        </Zona>
        <Zona nombre="abdomen derecho" totalInyecciones="1">
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
        <Zona nombre="muslo derecho" totalInyecciones="1">
            <EventoInyeccion tipo="Sin incidencia" cantidad="1"/>
        </Zona>
        <Zona nombre="triceps derecho" totalInyecciones="4">
            <EventoInyeccion tipo="Sin incidencia" cantidad="3"/>
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
        <Zona nombre="triceps izquierdo" totalInyecciones="15">
            <EventoInyeccion tipo="bola insulina" cantidad="1"/>
            <EventoInyeccion tipo="Sin incidencia" cantidad="14"/>
        </Zona>
        <Zona nombre="gluteo derecho" totalInyecciones="4">
            <EventoInyeccion tipo="bola insulina" cantidad="1"/>
            <EventoInyeccion tipo="Sin incidencia" cantidad="1"/>
            <EventoInyeccion tipo="dolor agudo" cantidad="1"/>
            <EventoInyeccion tipo="sangrado" cantidad="1"/>
        </Zona>
    </Zonas>
</Informe>
